### PR TITLE
fix(w1r3/java): move read buffer allocation outside loop

### LINKED ISSUE #139: [w1r3/java] Move allocation outside loop?
This seems to allocate a buffer over and over.  Maybe there is a way to share the same buffer until the download completes?

https://github.com/googleapis/storage-shared-benchmarking/blob/558b1ddb726b7a539934358191535a37ed860dba/w1r3/java/src/main/java/W1R3.java#L280-L282

### PR DESCRIPTION
**Pull request by BenWhitehead**
Fixes #139

### CODE REVIEW

**Review by coryan — APPROVED** [review]

File: w1r3/java/src/main/java/W1R3.java [hunk 1]
```diff
@@ -275,12 +277,12 @@ private void worker(
                   .startSpan();
           var downloadAttributes =
               Attributes.builder().putAll(meterAttributes).put("ssb_op", opName).build();
+          readBuffer.clear();
```
Comment (coryan) [inline w1r3/java/src/main/java/W1R3.java:280]: Should this go into the inner `while()` loop?

Comment (coryan) [reply w1r3/java/src/main/java/W1R3.java:280]: proposed that in #164
